debian/qemu-ifdown etc/
debian/tmp/usr/share/man/man1/qemu-system.1
debian/tmp/usr/share/qemu/keymaps
debian/tmp/usr/share/locale
debian/tmp/usr/share/qemu/trace-events-all
pc-bios/qemu-icon.bmp usr/share/qemu
pc-bios/qemu_logo_no_text.svg usr/share/qemu
# qemu-doc.html is duplicated here and in qemu metapackage
debian/tmp/usr/share/doc/qemu/qemu-doc.html usr/share/doc/qemu-system-common
debian/tmp/usr/share/doc/qemu/qmp-commands.txt usr/share/doc/qemu-system-common
